```{r, load_philipines_fit}
load(file = here::here("fits", "neg_binomial_73.Rdata"))
params <- extract(fit)
```


```{r, examine_values_converged_to}
parameter.names <- dimnames(fit)$parameters
pars <- parameter.names[grepl('mu_rho', parameter.names)]
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars) + 
scale_color_manual(values = c("blue", "red"))
traceplot(fit, inc_warmup = T, pars = pars) + 
scale_color_manual(values = c("blue", "red"))


pars <- parameter.names[grepl('w', parameter.names)]
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars) 
traceplot(fit, inc_warmup = T, pars = pars) 

pars <- parameter.names[grepl('^sigma_rho', parameter.names)]
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars)


pars <- parameter.names[grepl('^rho_j\\[7,', parameter.names) ]
print(fit, pars=pars)
all.p.k[7,] %>% log()
traceplot(fit, inc_warmup = T, pars = pars)

pars <- parameter.names[grepl('^sigma_delta', parameter.names) ]
print(fit, pars=pars)
traceplot(fit, inc_warmup = T, pars = pars)



pars <- parameter.names[grepl('^delta', parameter.names) ]
print(fit, pars=pars)


params$delta %>% colMeans %>% mean

pars <- c('rho_j[83,5]', 'rho_j[83,6]')
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars)

pars <- c('mu_rho[1]', 'mu_rho[3]', 'sigma_rho[6]', 'rho_j[7,6]')
print(fit, pars=pars)
mu.sigma.j.rho.plot <- traceplot(fit, inc_warmup = F, pars = pars, nrow=1) + theme_bw()

traceplot(fit, inc_warmup = F, pars = pars, nrow=1) + 
theme_bw() +
scale_color_manual(values = c("blue", "red"))

traceplot(fit, inc_warmup = F, pars = pars, nrow=1) + 
scale_color_manual(values = c("blue", "red"))

traceplot(fit, inc_warmup = T, pars = c('mu_rho[1]')) + 
scale_y_continuous(breaks=seq(2, 3, length.out=9), limits=c(2,3)) + 
scale_x_continuous(limits=c(200, 300))
```


```{r, saving_plots}
ggsave('traceplot_mu_sigma_j_rho.pdf', 
       plot= mu.sigma.j.rho.plot, width=9, height=5, units='in')


# library(gridExtra)
# pars <- parameter.names[grepl('^shape_delta', parameter.names)]
# print(fit, pars=pars)
# shape_plot <- traceplot(fit, inc_warmup = F, pars = pars) + theme_bw()

# pars <- parameter.names[grepl('^scale_delta', parameter.names)]
# print(fit, pars=pars)
# scale_plot <- traceplot(fit, inc_warmup = F, pars = pars) + theme_bw()
# shape_scale_plot <- grid.arrange(shape_plot, scale_plot, ncol=1)

# ggsave('visualisations/traceplot_shape_scale_delta_cauchy.pdf', 
#        plot= shape_scale_plot, width=6, height=5, units='in')
```

```{r, region_specific_errors}
parameter.names <- dimnames(fit)$parameters
pars <- parameter.names[grepl('^rho_j\\[140,', parameter.names) ]

# pars <- parameter.names[grepl('^rate_rho', parameter.names) ]
# pars
print(fit, pars=pars)
# traceplot(fit, inc_warmup = TRUE, pars = pars)

all.p.k[140,] %>% log()

for(region in 1:num.regions){
  pars <- parameter.names[grepl(paste0('^rho_j\\[', region), parameter.names) ]
  print(fit, pars=pars)
  print(paste('True prevalence for region', region, 'is', all.p.k[region,] %>% log()))
}
```


```{r, disperson_of_groups}
parameter.names <- dimnames(fit)$parameters
pars <- parameter.names[grepl('w', parameter.names)]
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars) 
traceplot(fit, inc_warmup = T, pars = pars) 

pars <- parameter.names[grepl('mu_rho', parameter.names)]
print(fit, pars=pars)
traceplot(fit, inc_warmup = F, pars = pars) 
traceplot(fit, inc_warmup = T, pars = pars) 
```
