// Generated by rstantools.  Do not edit by hand.

/*
    subnationalPrev is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    subnationalPrev is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with subnationalPrev.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_neg_binomial_partial_pooling_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 44> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 9, column 2 to column 41)",
  " (in 'string', line 10, column 2 to column 38)",
  " (in 'string', line 11, column 2 to column 41)",
  " (in 'string', line 13, column 2 to column 46)",
  " (in 'string', line 14, column 2 to column 33)",
  " (in 'string', line 15, column 2 to column 33)",
  " (in 'string', line 18, column 2 to column 41)",
  " (in 'string', line 19, column 2 to column 40)",
  " (in 'string', line 20, column 2 to column 42)",
  " (in 'string', line 22, column 4 to column 52)",
  " (in 'string', line 23, column 4 to column 43)",
  " (in 'string', line 25, column 6 to column 47)",
  " (in 'string', line 24, column 17 to line 26, column 5)",
  " (in 'string', line 24, column 4 to line 26, column 5)",
  " (in 'string', line 21, column 2 to line 27, column 3)",
  " (in 'string', line 30, column 2 to column 25)",
  " (in 'string', line 31, column 2 to column 27)",
  " (in 'string', line 33, column 4 to column 42)",
  " (in 'string', line 32, column 15 to line 34, column 3)",
  " (in 'string', line 32, column 2 to line 34, column 3)",
  " (in 'string', line 35, column 2 to column 35)",
  " (in 'string', line 36, column 2 to column 20)",
  " (in 'string', line 38, column 4 to column 40)",
  " (in 'string', line 37, column 15 to line 39, column 3)",
  " (in 'string', line 37, column 2 to line 39, column 3)",
  " (in 'string', line 2, column 2 to column 22)",
  " (in 'string', line 3, column 2 to column 22)",
  " (in 'string', line 4, column 8 to column 9)",
  " (in 'string', line 4, column 10 to column 11)",
  " (in 'string', line 4, column 2 to column 13)",
  " (in 'string', line 5, column 2 to column 22)",
  " (in 'string', line 6, column 9 to column 10)",
  " (in 'string', line 6, column 2 to column 44)",
  " (in 'string', line 9, column 38 to column 39)",
  " (in 'string', line 9, column 28 to column 29)",
  " (in 'string', line 10, column 28 to column 29)",
  " (in 'string', line 11, column 28 to column 29)",
  " (in 'string', line 14, column 24 to column 25)",
  " (in 'string', line 15, column 28 to column 29)",
  " (in 'string', line 18, column 28 to column 29)",
  " (in 'string', line 19, column 28 to column 29)",
  " (in 'string', line 20, column 39 to column 40)",
  " (in 'string', line 20, column 28 to column 29)"};
#include <stan_meta_header.hpp>
class model_neg_binomial_partial_pooling final : public model_base_crtp<model_neg_binomial_partial_pooling> {
private:
  int N;
  int K;
  std::vector<std::vector<int>> y;
  int J;
  std::vector<int> jj;
public:
  ~model_neg_binomial_partial_pooling() {}
  model_neg_binomial_partial_pooling(stan::io::var_context& context__,
                                     unsigned int random_seed__ = 0,
                                     std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_neg_binomial_partial_pooling_namespace::model_neg_binomial_partial_pooling";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 26;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 27;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("y", "K", K);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      y = std::vector<std::vector<int>>(N,
            std::vector<int>(K, std::numeric_limits<int>::min()));
      {
        std::vector<int> y_flat__;
        current_statement__ = 30;
        y_flat__ = context__.vals_i("y");
        current_statement__ = 30;
        pos__ = 1;
        current_statement__ = 30;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 30;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 30;
            stan::model::assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 30;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 31;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 31;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("jj", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "jj", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      jj = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 33;
      jj = context__.vals_i("jj");
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "jj", jj, 1);
      current_statement__ = 33;
      stan::math::check_less_or_equal(function__, "jj", jj, J);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("rho_j", "J", J);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("rho_j", "K", K);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("mu_rho", "K", K);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("sigma_rho", "K", K);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("delta", "N", N);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("w", "K", K);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("shape_rho", "K", K);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("rate_rho", "K", K);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("lambda", "N", N);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("lambda", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (J * K) + K + K + 1 + N + K;
  }
  inline std::string model_name() const final {
    return "model_neg_binomial_partial_pooling";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_neg_binomial_partial_pooling_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,1,-1>> rho_j =
        std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>(J,
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__));
      current_statement__ = 1;
      rho_j = in__.template read_constrain_lb<
                std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>,
                jacobian__>(0, lp__, J, K);
      Eigen::Matrix<local_scalar_t__,1,-1> mu_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      mu_rho = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0, lp__,
                 K);
      Eigen::Matrix<local_scalar_t__,1,-1> sigma_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      sigma_rho = in__.template read_constrain_lb<
                    Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0,
                    lp__, K);
      local_scalar_t__ sigma_delta = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_delta = in__.template read_constrain_lub<local_scalar_t__,
                      jacobian__>(0, 1.5, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 5;
      delta = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, N);
      Eigen::Matrix<local_scalar_t__,1,-1> w =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 6;
      w = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0, lp__, K);
      Eigen::Matrix<local_scalar_t__,1,-1> shape_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,1,-1> rate_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      std::vector<Eigen::Matrix<local_scalar_t__,1,-1>> lambda =
        std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>(N,
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__));
      {
        current_statement__ = 10;
        stan::model::assign(shape_rho,
          stan::math::elt_divide(stan::math::square(mu_rho),
            stan::math::square(sigma_rho)), "assigning variable shape_rho");
        current_statement__ = 11;
        stan::model::assign(rate_rho,
          stan::math::elt_divide(mu_rho, stan::math::square(sigma_rho)),
          "assigning variable rate_rho");
        current_statement__ = 14;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 12;
          stan::model::assign(lambda,
            stan::math::exp(
              stan::math::subtract(
                stan::model::rvalue(delta, "delta", stan::model::index_uni(n)),
                stan::model::rvalue(rho_j, "rho_j",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
            "assigning variable lambda", stan::model::index_uni(n));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "shape_rho", shape_rho,
        0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "rate_rho", rate_rho, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      {
        current_statement__ = 16;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu_rho, 0, 10));
        current_statement__ = 17;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(sigma_rho));
        current_statement__ = 20;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 18;
          lp_accum__.add(stan::math::gamma_lpdf<propto__>(
                           stan::model::rvalue(rho_j, "rho_j",
                             stan::model::index_uni(j)), shape_rho, rate_rho));
        }
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(delta, 5.5,
                         sigma_delta));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(w, 0, 10));
        current_statement__ = 25;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 23;
          lp_accum__.add(stan::math::neg_binomial_2_lpmf<propto__>(
                           stan::model::rvalue(y, "y",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(lambda, "lambda",
                             stan::model::index_uni(n)), w));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_neg_binomial_partial_pooling_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<double,1,-1>> rho_j =
        std::vector<Eigen::Matrix<double,1,-1>>(J,
          Eigen::Matrix<double,1,-1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      rho_j = in__.template read_constrain_lb<
                std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>,
                jacobian__>(0, lp__, J, K);
      Eigen::Matrix<double,1,-1> mu_rho =
        Eigen::Matrix<double,1,-1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      mu_rho = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0, lp__,
                 K);
      Eigen::Matrix<double,1,-1> sigma_rho =
        Eigen::Matrix<double,1,-1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      sigma_rho = in__.template read_constrain_lb<
                    Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0,
                    lp__, K);
      double sigma_delta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_delta = in__.template read_constrain_lub<local_scalar_t__,
                      jacobian__>(0, 1.5, lp__);
      Eigen::Matrix<double,-1,1> delta =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      delta = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, N);
      Eigen::Matrix<double,1,-1> w =
        Eigen::Matrix<double,1,-1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      w = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,1,-1>, jacobian__>(0, lp__, K);
      Eigen::Matrix<double,1,-1> shape_rho =
        Eigen::Matrix<double,1,-1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,1,-1> rate_rho =
        Eigen::Matrix<double,1,-1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,1,-1>> lambda =
        std::vector<Eigen::Matrix<double,1,-1>>(N,
          Eigen::Matrix<double,1,-1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN()));
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          out__.write(rho_j[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(mu_rho);
      out__.write(sigma_rho);
      out__.write(sigma_delta);
      out__.write(delta);
      out__.write(w);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      {
        current_statement__ = 10;
        stan::model::assign(shape_rho,
          stan::math::elt_divide(stan::math::square(mu_rho),
            stan::math::square(sigma_rho)), "assigning variable shape_rho");
        current_statement__ = 11;
        stan::model::assign(rate_rho,
          stan::math::elt_divide(mu_rho, stan::math::square(sigma_rho)),
          "assigning variable rate_rho");
        current_statement__ = 14;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 12;
          stan::model::assign(lambda,
            stan::math::exp(
              stan::math::subtract(
                stan::model::rvalue(delta, "delta", stan::model::index_uni(n)),
                stan::model::rvalue(rho_j, "rho_j",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
            "assigning variable lambda", stan::model::index_uni(n));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "shape_rho", shape_rho,
        0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "rate_rho", rate_rho, 0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      if (emit_transformed_parameters__) {
        out__.write(shape_rho);
        out__.write(rate_rho);
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            out__.write(lambda[(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,1,-1>> rho_j =
        std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>(J,
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        current_statement__ = 1;
        for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
          current_statement__ = 1;
          stan::model::assign(rho_j, in__.read<local_scalar_t__>(),
            "assigning variable rho_j", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_lb(0, rho_j);
      Eigen::Matrix<local_scalar_t__,1,-1> mu_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(mu_rho,
        in__.read<Eigen::Matrix<local_scalar_t__,1,-1>>(K),
        "assigning variable mu_rho");
      out__.write_free_lb(0, mu_rho);
      Eigen::Matrix<local_scalar_t__,1,-1> sigma_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(sigma_rho,
        in__.read<Eigen::Matrix<local_scalar_t__,1,-1>>(K),
        "assigning variable sigma_rho");
      out__.write_free_lb(0, sigma_rho);
      local_scalar_t__ sigma_delta = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_delta = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1.5, sigma_delta);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(delta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable delta");
      out__.write_free_lb(0, delta);
      Eigen::Matrix<local_scalar_t__,1,-1> w =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(w,
        in__.read<Eigen::Matrix<local_scalar_t__,1,-1>>(K),
        "assigning variable w");
      out__.write_free_lb(0, w);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "rho_j", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "mu_rho", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma_rho",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_delta",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "delta", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,1,-1>> rho_j =
        std::vector<Eigen::Matrix<local_scalar_t__,1,-1>>(J,
          Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> rho_j_flat__;
        current_statement__ = 1;
        rho_j_flat__ = context__.vals_r("rho_j");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(rho_j, rho_j_flat__[(pos__ - 1)],
              "assigning variable rho_j", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lb(0, rho_j);
      Eigen::Matrix<local_scalar_t__,1,-1> mu_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_rho_flat__;
        current_statement__ = 2;
        mu_rho_flat__ = context__.vals_r("mu_rho");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(mu_rho, mu_rho_flat__[(pos__ - 1)],
            "assigning variable mu_rho", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, mu_rho);
      Eigen::Matrix<local_scalar_t__,1,-1> sigma_rho =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_rho_flat__;
        current_statement__ = 3;
        sigma_rho_flat__ = context__.vals_r("sigma_rho");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(sigma_rho, sigma_rho_flat__[(pos__ - 1)],
            "assigning variable sigma_rho", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma_rho);
      local_scalar_t__ sigma_delta = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_delta = context__.vals_r("sigma_delta")[(1 - 1)];
      out__.write_free_lub(0, 1.5, sigma_delta);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> delta_flat__;
        current_statement__ = 5;
        delta_flat__ = context__.vals_r("delta");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(delta, delta_flat__[(pos__ - 1)],
            "assigning variable delta", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, delta);
      Eigen::Matrix<local_scalar_t__,1,-1> w =
        Eigen::Matrix<local_scalar_t__,1,-1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 6;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, w);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"rho_j", "mu_rho", "sigma_rho",
                "sigma_delta", "delta", "w"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"shape_rho", "rate_rho", "lambda"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(J),
                                                 static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "rho_j" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_rho" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_rho" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_delta");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "shape_rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "rate_rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "lambda" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "rho_j" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_rho" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_rho" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_delta");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "delta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "shape_rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "rate_rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "lambda" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho_j\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"parameters\"},{\"name\":\"mu_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"shape_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rate_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho_j\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(J) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"parameters\"},{\"name\":\"mu_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma_delta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"shape_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rate_rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((J * K) + K) + K) + 1) + N) + K);
    const size_t num_transformed = emit_transformed_parameters * (((K + K) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((J * K) + K) + K) + 1) + N) + K);
    const size_t num_transformed = emit_transformed_parameters * (((K + K) +
      (N * K)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_neg_binomial_partial_pooling_namespace::model_neg_binomial_partial_pooling;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_neg_binomial_partial_pooling_namespace::profiles__;
}
#endif
#endif
